### ISSUE TITLE
Any plans on updating?

### ISSUE THREAD

**Issue by Jay9519** [prism/OreAlerts#10]
I've recently updated my server to 1.11.2 but unfortunately this great mod doesn't work anymore :(
Any plans on updating it to work for 1.11.2 sponge?

**Comment by viveleroi** [comment]
I haven't been made aware of any changes that would impact this plugin. It stills compiles just fine so the API hasn't changed. Are you getting errors?

**Comment by viveleroi** [comment]
I haven't tried it personally but it compiles without issue, no one has reported specific errors, so it should be working.
