### ISSUE TITLE
Server won't load with this plugin installed

### ISSUE THREAD

**Issue by Jay9519** [prism/OreAlerts#7]
SpongeForge-1.10.2-2281-5.2.0-BETA-2315
OreAlerts-1.1

I'm assuming the mod needs updating as it seems to be very old?

**Comment by viveleroi** [comment]
Try this: https://github.com/prism/OreAlerts/releases/tag/1.2

I had yet to release an update since someone submitted PRs to update us to SpongeAPI 6.

**Comment by Jay9519** [comment]
Thank you for the fast reply, works perfectly
any plans on integrating the alerts to work with other mods and the ores in them like Biomes O Plenty?
