### ISSUE TITLE
Not compatible with LuckPerms?

### ISSUE THREAD

**Issue by Jay9519** [prism/OreAlerts#9]
I recently changed from pex to luckperms for my sponge modded serverand unfortunately it doesn't work anymore.
I have added the correct permission to the admin group orealerts.receive

SpongeForge 1.10.2 2353
OreAlerts 1.0
LuckPerms 3.2.6

**Comment by viveleroi** [comment]
You'll need to speak with LuckyPerms, we don't code against specific permissions systems.
